folderNames:
  dstPath: ./results
  normPath: ./${.dstPath}/normalized
  maskPath: ./${.dstPath}/mask
  upperPath: ./${.dstPath}/upperEyelidMask
  lowerPath: ./${.dstPath}/lowerEyelidMask
  reflPath: ./${.dstPath}/reflectionMask

dataset:
  filePathsREGEX: ./UTIRIS/RGB Images/*/*.JPG
  color: True
