name: untrained_conv

_target_: neural.lit_modules.Classifier
learning_rate: 
    1e-3
classifier:
    _target_: neural.lit_modules.UntrainedConvNet
    num_classes: 
        79
    image_height:  100
    image_width:  600
    activation:
        _target_: 
            torch.nn.LeakyReLU
    dropout: 
        0.2
    max_num_channels:
        256
    stride:
        1       
    num_convnet_layers: 
        5
