name: untrained_conv

_target_: neural.lit_modules.ConvNetClassifier
num_classes: 
    79
image_width:  600
image_height:  100
num_convnet_layers: 
    6
activation:
    _target_: 
        torch.nn.LeakyReLU
dropout: 
    0.2
learning_rate: 
    1e-3
max_num_channels:
    256
